server.port=5000

# PostgreSQL Connection Properties
spring.datasource.url=jdbc:postgresql://localhost:5432/urban_ride_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# CORS & Custom JWT Settings
jwt.secret=urban_ride_mobility_super_secret_jwt_key_2026_spring_boot_64byte
jwt.expiration=86400000
