package com.urbanride.enums;

public enum RideStatus {
    REQUESTED,
    SEARCHING_DRIVER,
    DRIVER_ASSIGNED,
    DRIVER_ARRIVING,
    DRIVER_ARRIVED,
    RIDE_STARTED,
    COMPLETED,
    CANCELLED_BY_RIDER,
    CANCELLED_BY_DRIVER
}
