server.port=8084

spring.application.name=PAYMENT-SERVICE

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# PostgreSQL Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/urban_payment_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
